app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask.ext.login import UserMixin
from flaskext.couchdb import Document, TextField, DateTimeField, ViewField, paginate
from . import login_manager


class User(UserMixin, Document):
    doc_type = 'user'
    
    email = "aaa@bbb.cc" 
    username = "test" 
    is_admin = True
    password_hash = ""
    name = "Test User"

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        password = "test"

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)



@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class Talk(Document):
    doc_type = 'talk'
    
    title = TextField()
    description = TextField()

    all = ViewField('guestbook', '''
        function (doc) {
            if (doc.doc_type == 'talk') {
                emit(doc.time, doc);
            };
        }''', descending=True)
 
    
    

app/talks/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, TextAreaField, BooleanField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.validators import Optional, Length, Required, URL, Email
from flask.ext.pagedown.fields import PageDownField


class ProfileForm(Form):
    name = StringField('Name', validators=[Optional(), Length(1, 64)])
    location = StringField('Location', validators=[Optional(), Length(1, 64)])
    bio = TextAreaField('Bio')
    submit = SubmitField('Submit')


class TalkForm(Form):
    title = StringField('Title', validators=[Required(), Length(1, 128)])
    description = TextAreaField('Description')
    slides = StringField('Slides Embed Code (450 pixels wide)')
    video = StringField('Video Embed Code (450 pixels wide)')
    venue = StringField('Venue',
                        validators=[Required(), Length(1, 128)])
    venue_url = StringField('Venue URL',
                            validators=[Optional(), Length(1, 128), URL()])
    date = DateField('Date')
    submit = SubmitField('Submit')

    def from_model(self, talk):
        self.title.data = talk.title
        self.description.data = talk.description
        self.slides.data = talk.slides
        self.video.data = talk.video
        self.venue.data = talk.venue
        self.venue_url.data = talk.venue_url
        self.date.data = talk.date

    def to_model(self, talk):
        talk.title = self.title.data
        talk.description = self.description.data
        talk.slides = self.slides.data
        talk.video = self.video.data
        talk.venue = self.venue.data
        talk.venue_url = self.venue_url.data
        talk.date = self.date.data


class PresenterCommentForm(Form):
    body = PageDownField('Comment', validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(Form):
    name = StringField('Name', validators=[Required(), Length(1, 64)])
    email = StringField('Email', validators=[Required(), Length(1, 64),
                                             Email()])
    body = PageDownField('Comment', validators=[Required()])
    notify = BooleanField('Notify when new comments are posted', default=True)
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.login import LoginManager
from flaskext.couchdb import CouchDBManager, Document, TextField, DateTimeField, ViewField, paginate
from config import config


bootstrap = Bootstrap()

couchdb_manager = CouchDBManager()

login_manager = LoginManager()
login_manager.login_view = 'auth.login'


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    
    from models import User, Talk
    couchdb_manager.add_document(User)
    couchdb_manager.add_document(Talk)
    couchdb_manager.setup(app)
    couchdb_manager.sync(app)
    
    login_manager.init_app(app)

    from .talks import talks as talks_blueprint
    app.register_blueprint(talks_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/talks/__init__.py
from flask import Blueprint

talks = Blueprint('talks', __name__)

from . import routes

app/talks/routes.py
from flask import render_template, flash, redirect, url_for, abort,\
    request, current_app
from flask.ext.login import login_required, current_user
from ..models import User, Talk
from . import talks
from .forms import ProfileForm, TalkForm, CommentForm, PresenterCommentForm


@talks.route('/')
def index():
    talks = Talk.all();
    return render_template('talks/index.html', talks=talks)


@talks.route('/user/<username>')
def user(username):
    user = User()
    return render_template('talks/user.html', user=user)


@talks.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = ProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        flash('Your profile has been updated.')
        return redirect(url_for('talks.user', username=current_user.username))
    form.name.data = current_user.name
    return render_template('talks/profile.html', form=form)


@talks.route('/new', methods=['GET', 'POST'])
@login_required
def new_talk():
    form = TalkForm()
    if form.validate_on_submit():
        talk = Talk()
        form.to_model(talk)
        flash('The talk was added successfully.')
        return redirect(url_for('.index'))
    return render_template('talks/edit_talk.html', form=form)


@talks.route('/talk/<id>', methods=['GET', 'POST'])
def talk(id):
    talk = Talk.load(id) 
    return render_template('talks/talk.html', talk=talk)


@talks.route('/edit/<id>', methods=['GET', 'POST'])
@login_required
def edit_talk(id):
    talk = Talk.load(id)
    form = TalkForm()
    if form.validate_on_submit():
        form.to_model(talk)
        flash('The talk was updated successfully.')
        return redirect(url_for('.talk', id=talk.id))
    form.from_model(talk)
    return render_template('talks/edit_talk.html', form=form)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Talks{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-default" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('talks.index') }}">Talks</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('talks.index') }}">Home</a></li>
                {% if current_user.is_authenticated() %}
                <li><a href="{{ url_for('talks.user', username=current_user.username) }}">Profile</a></li>
                <li><a href="{{ url_for('talks.new_talk') }}">New Talk</a></li>
                {% set moderation_count = current_user.for_moderation().count() %}
                <li>
                    <a href="{{ url_for('talks.moderate') }}">Moderate
                        {% if moderation_count %}
                        <span class="badge badge-red">{{ moderation_count }}</span>
                        {% endif %}
                    </a>
                </li>
                {% if current_user.is_admin %}
                    {% set admin_moderation_count = current_user.for_moderation(True).count() %}
                    <li>
                        <a href="{{ url_for('talks.moderate_admin') }}">Moderate [Admin]
                            {% if admin_moderation_count %}
                            <span class="badge badge-red">{{ admin_moderation_count }}</span>
                            {% endif %}
                        </a>
                    </li>
                {% endif %}
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if not current_user.is_authenticated() %}
                <li><a href="{{ url_for('auth.login') }}">Presenter Login</a></li>
                {% else %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{{ current_user.gravatar(size=18) }}"> {{ current_user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                    </ul>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/talks/_comment.html
<p>
    {% if comment.author %}
        {% if index %}
        <span class="label label-primary">#{{ index }}</span>
        {% endif %}
        <a href="{{ url_for('.user', username=comment.author.username) }}">{{ comment.author.username }}</a>
    {% else %}
        {% if talk.author == current_user or current_user.is_admin %}
            {% if not comment.approved %}
            <div id="moderate-{{ comment.id }}" class="pull-right">
                <a class="btn btn-primary api-approve" data-id="{{ comment.id }}" href="#"><span class="glyphicon glyphicon-ok"></span> Approve</a>
                <a class="btn btn-danger api-delete" data-id="{{ comment.id }}" href="#"><span class="glyphicon glyphicon-trash"></span> Delete</a>
            </div>
            <div id="approved-{{ comment.id }}" class="pull-right" style="display: none;">
                <span class="glyphicon glyphicon-ok"></span> <b>Approved</b>
            </div>
            <div id="deleted-{{ comment.id }}" class="pull-right" style="display: none;">
                <span class="glyphicon glyphicon-trash"></span> <b>Deleted</b>
            </div>
            {% endif %}
        {% endif %}
        {% if index %}
        <span class="label label-default">#{{ index }}</span>
        {% endif %}
        <b>{{ comment.author_name }}</b>
        {% if current_user.is_authenticated() and (talk.author == current_user or current_user.is_admin) %}
        (<a href="mailto:{{ comment.author_email }}">{{ comment.author_email }}</a>)
        {% endif %}
    {% endif %}
    commented {{ moment(comment.timestamp).fromNow() }}:
</p>
<div class="comment-body">
    {{ comment.body_html | safe }}
</div>

app/templates/talks/_comments.html
<ul class="comment-list">
{% if pagination %}
    {% set base_index = (pagination.page - 1) * pagination.per_page %}
{% else %}
    {% set base_index = 0 %}
{% endif %}
{% for comment in comments %}
    {% set index = loop.index + base_index %}
    <li class="comment">
        {% include "talks/_comment.html" %}
    </li>
{% endfor %}
</ul>

app/templates/talks/_talk_header.html
<div class="talk-header">
    {% if talk.author == current_user %}
    <a class="btn btn-primary pull-right" href="{{ url_for('talks.edit_talk', id=talk.id) }}">Edit</a>
    {% elif current_user.is_admin %}
    <a class="btn btn-danger pull-right" href="{{ url_for('talks.edit_talk', id=talk.id) }}">Edit</a>
    {% endif %}
    <h2><a href="{{ url_for('talks.talk', id=talk.id) }}">{{ talk.title }}</a></h2>
    <h3>{{ talk.description }}</h3>
    <div class="pull-right"><a href="{{ url_for('talks.talk', id=talk.id) }}#comments"></a></div>
</div>

app/templates/talks/_talks.html
<ul class="talk-list">
{% for talk in talks %}
    <li class="talk">
    {% include "talks/_talk_header.html" %}
    </li>
{% endfor %}
</ul>

app/templates/talks/edit_talk.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Talk</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/talks/index.html
{% extends "base.html" %}

{% block page_content %}
{% include "talks/_talks.html" %}

{% endblock %}

app/templates/talks/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Profile</h1>
</div>
{{ wtf.quick_form(form) }}
{% endblock %}

app/templates/talks/talk.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    {% include "talks/_talk_header.html" %}
</div>
{% endblock %}

app/templates/talks/user.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header user-profile">
    <div class="user-avatar"><img src="{{ user.gravatar(128) }}"></div>
    {% if current_user == user %}<a class="btn btn-default pull-right" href="{{ url_for('talks.profile') }}">Edit Profile</a>{% endif %}
    <h1>{{ user.username }}</h1>
    <p>
        {% if user.name %}{{ user.name }}<br>{% endif %}
        {% if user.location %}<a href="http://maps.google.com?q={{ user.location }}">{{ user.location }}</a><br>{% endif %}
    </p>
    {% if user.bio %}<p>{{ user.bio }}</p>{% endif %}
</div>
{% include "talks/_talks.html" %}
{% if talks %}
<ul class="pager">
    {% if pagination.has_prev %}
    <li class="previous"><a href="{{ url_for('talks.user', username=user.username, page=pagination.prev_num) }}">&larr; Newer</a></li>
    {% else %}
    <li class="previous disabled"><a href="#">&larr; Newer</a></li>
    {% endif %}
    {% if pagination.has_next %}
    <li class="next"><a href="{{ url_for('talks.user', username=user.username, page=pagination.next_num) }}">Older &rarr;</a></li>
    {% else %}
    <li class="next disabled"><a href="#">Older &rarr;</a></li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}